### ISSUE TITLE
Minor feature request: Unique favicon

### ISSUE THREAD

**Issue by rootwork** [simplytestme/website#155]
A minor feature request to swap out the favicon for simplytestme for something other than the d.o favicon (maybe the "s" druplicon from the simplytestme home page?) so that it's easier to know which tab is the right one. 

When I'm switching back and forth between tabs reviewing an issue, having the same favicon makes it harder to keep track, especially if I have other d.o issues or docs pages open in other tabs. Contrast to e.g. DrupalPod where those tabs have the GitPod favicon so I can spot them right away.

**Comment by mglaman** [comment]
Moving to d.o issue: https://www.drupal.org/project/simplytest/issues/3423291
