### ISSUE TITLE
Display Drupal core versions descending

### ISSUE THREAD

**Issue by mglaman** [simplytestme/website#270]
10.0.x shows on the bottom, after 9.0.x. We need to reverse the ordering.

Logic: https://github.com/simplytestme/website/blob/main/web/modules/custom/simplytest_projects/src/CoreVersionManager.php#L69C23-L79

It is using `DESC` but doesn't seem to be working correctly.

**Comment by sonvir249** [comment]
@mglaman raised a PR to fix this issue: https://github.com/simplytestme/website/pull/276
