### ISSUE TITLE
Add support for Lando

### ISSUE THREAD

**Issue by nerdstein** [simplytestme/website#4]
Please add instructions and a .lando.yml file defintiion

**Comment by nerdstein** [comment]
`lando drush si simplytest --existing-config --account-pass=admin --yes`

**Comment by sushyl** [comment]
Here's the PR with the Lando YAML and README changes.
https://github.com/mglaman/simplytestme/pull/6

**Comment by nerdstein** [comment]
```
$databases['default']['default'] = array (
  'database' => 'drupal8',
  'username' => 'drupal8',
  'password' => 'drupal8',
  'prefix' => '',
  'host' => 'database',
  'port' => '3306',
  'namespace' => 'Drupal\\Core\\Database\\Driver\\mysql',
  'driver' => 'mysql',
);
```

**Comment by hotwebmatter** [comment]
I forked the project and I'm adding the `.lando.yml` from [this project](https://github.com/oomphinc/drupal-scaffold).

It will need some code review.

**Comment by hotwebmatter** [comment]
Here's my PR: https://github.com/mglaman/simplytestme/pull/7

**Comment by hotwebmatter** [comment]
Yup! The difference is that while I was working on #7 I pasted a snippet in Slack chat as a starting point, which is #6 (so please merge #7)

Thanks @mglaman !

**Comment by hotwebmatter** [comment]
Hmm, also the other difference is that @benjifisher carried my PR over the finish line 🎉
