### ISSUE TITLE
Add theming automation in here

### ISSUE THREAD

**Issue by nerdstein** [simplytestme/website#5]
Can we have the DDEV and Lando work show how to automatically load a theme? Could it load the right node version and run the correct commands to load a theme?

**Comment by mglaman** [comment]
> Can we have the DDEV and Lando work show how to automatically load a theme?

What do you mean by load a theme? The compilation of assets?

> Could it load the right node version and run the correct commands to load a theme?

Yeah, both can be used to compile the assets so you don't need nodejs locally

**Comment by mglaman** [comment]
Closing – not sure if this was for our theme or the building of a contrib theme.
